name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Any CPU]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: MSBuild of plugin dll
      working-directory: .\
      run: msbuild XmlNavigator.sln /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - uses: olegtarasov/get-tag@v2.1.2
      id: tagName

    - name: zip artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      run: 7z a XmlNavigator_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip .\build\${{ matrix.build_platform }}\${{ matrix.build_configuration }}\NppDocShare.dll

    - name: Archive artifacts for ${{ matrix.build_platform }}
      if: matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v3
      with:
          name: XmlNavigator_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip
          path: XmlNavigator_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip

    - name: Create release on tagging
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: XmlNavigator_${{ steps.tagName.outputs.tag }}_${{ matrix.build_platform }}.zip

